s = 'hello'
# print(len(s))
# print(s.capitalize())
# s2 = s.capitalize()
# print(s,s2)
# print(s.center(20))
# print(s.count('l', 0,4))
# print(s.find('a'))
# print(s.replace('l', 't'))
# print(s.split(' '))
# print(s.isdigit())